# exceptions.py

class MathError(Exception):
    pass
